version: "3"
services:
  redis:
    image: redis:6.0.6
    networks:
      - mp_network
    ports:
    - 6379:6379
  api:
    build:
      context: express
    depends_on:
      - redis
    ports:
    - 8080:8080
    environment:
      REDIS_HOST: redis
    networks:
      - mp_network
  web:
    build:
      context: vue
    depends_on:
      - api
    ports:
    - 9001:80
    networks:
      - mp_network
networks:
  mp_network: